[versions]
agp = "9.2.1"
espresso = "3.7.0"
gson = "2.13.2"
junit = "4.13.2"
androidxJunit = "1.3.0"
mmkv = "2.4.1"
work = "2.11.2"

[libraries]
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxJunit" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
mmkv = { group = "com.tencent", name = "mmkv", version.ref = "mmkv" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
